name: Linting Code
on:
    push:
        branches: ['main']
jobs:
    lint:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install dependencies
              run: npm ci
            - name: Lint code
              run: npm run lint
